services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: scraper_app
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    command: ["python", "-m", "app.main"]

volumes:
  postgres_data:
